name: mobile_os_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  record: ^6.0.0
  path: ^1.9.1
  just_audio: ^0.10.1
  stylish_bottom_bar: ^1.1.1
  flutter_analog_clock: ^1.0.3
  intl: ^0.20.2
  bottom_picker: ^3.2.0
  alarm: ^5.1.3
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  animations: ^2.0.11
  table_calendar: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/PlayfairDisplay-Regular.ttf
          style: normal

    - family: Raleway
      fonts:
        - asset: lib/assets/fonts/Raleway-Regular.ttf
          style: normal

    - family: CalSans
      fonts:
        - asset: lib/assets/fonts/CalSans-Regular.ttf
          style: normal
  assets:
    - lib/assets/images/
    - lib/assets/sounds/startupSound.mp3
    - .env
