name: mobile_os_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  record: ^6.0.0
  path: ^1.9.1
  just_audio: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
